spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory_db?user=inventory_user&password=inventory_password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inventory-group
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.initialization-mode=always
#  spring.kafka.bootstrap-servers=kafka:9092
#  spring.kafka.consumer.group-id=my-group
